_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'mdg' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'mdg', 'MDG']
  IMG_SIZE: 64
  CROP_SIZE: 0
  NUM_WORKERS: 30
OUTPUT:
  DIR: './output_dir/sa_base_adam_mdg_1000e/'
TRAIN:
  OPTIMIZER: 'adam'
MODEL:
  SLOT:
    NUM: 6
  ENC_DEPTH: 4
  DEC_DEPTH: 4
  DEC_INIT_SIZE: 64
  HID_DIM: 32
  MLP_HID_DIM: 128