_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'objr' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'MOVi', 'movi']
  IMG_SIZE: 64
  NUM_WORKERS: 30
OUTPUT:
  DIR: './output_dir/objr_ask_ippe123_0.1_0.5/'
TRAIN:
  EPOCHS: 800
  BATCH_SIZE: 256
  POS_LOSS_WEIGHT: 0.01
  OPTIMIZER: 'adam'
WEAK_SUP:
  TYPE: "bbox_center"
  USE_NO_OBJ: False
  RANDOM_PROP: 0.5
  RAND_POS_TYPE: "uniform" # it can be "standard_gaussian"
  INIT_USING_SUP: False
  SPLIT:
    RATIO: 0.1
    TRAIN:
      MODE: 'batch_fusion' # ['','interval', 'epoch_ranges', 'batch_fusion']
      BATCH_FUSION_RATIO: 0.25
POS_PRED:
  USE_POS_PRED: True
  USE_GT: True
  POS_ENC_MODE: "learnable"
  LOCATIONS: [1,2,3] # -1 to last one, 1,2,3,.. to iteration number # TODO: name of variable?
MODEL:
  SLOT:
    ATTN_SMOOTH: "normed_softmax"