_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'movi' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'mdg', 'MDG', 'movi', 'MOVi', 'MOVI']
  IMG_SIZE: 128
  CROP_SIZE: 0
  NUM_WORKERS: 30
OUTPUT:
  DIR: './output_dir/movi_temperature_5.0/'
MODEL:
  SLOT:
    TEMPERATURE: 5.0