_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'movi' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'msn', 'MSN']
  IMG_SIZE: 128
  NUM_WORKERS: 30
OUTPUT:
  DIR: './output_dir/movi_ask_gau_big_sigma/'
TRAIN:
  OPTIMIZER: 'adam'
MODEL:
  SLOT:
    ATTN_SMOOTH: "gaussian"
    ATTN_SMOOTH_GAU_MIN: 1.0
    ATTN_SMOOTH_GAU_MAX: 5.0