_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'movi' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'mdg', 'MDG', 'movi', 'MOVi', 'MOVI']
  IMG_SIZE: 64
  CROP_SIZE: 0
  NUM_WORKERS: 30
OUTPUT:
  DIR: './output_dir/sa_base_sup_box_no_obj_movi_1000e/'
WEAK_SUP:
  TYPE: 'bbox' # ['', 'bbox', 'bbox_center']
  USE_NO_OBJ: True # TODO: find alternative for the variable name 'use_no_obj'
  INIT_USING_SUP: True
  
