_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'movi' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'MOVi', 'movi']
  IMG_SIZE: 128
  NUM_WORKERS: 30
TRAIN:
  OPTIMIZER: 'adam'
OUTPUT:
  DIR: './output_dir/sa_base_v0_adam_movi_1000e/'