_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'movi' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'mdg', 'MDG', 'movi', 'MOVi', 'MOVI']
  IMG_SIZE: 128
  CROP_SIZE: 0
  NUM_WORKERS: 30
OUTPUT:
  DIR: './output_dir/sa_huge_movi_1000e/'
MODEL:
  SLOT:
    NUM: 7
    DIM: 512
    ITERATIONS: 3
    ATTN_HEADS: 8
    TEMPERATURE: 1.0
  ENC_DEPTH: 12
  DEC_DEPTH: 12
  HID_DIM: 256
  MLP_HID_DIM: 256