_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'movi' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'msn', 'MSN']
  IMG_SIZE: 128
  NUM_WORKERS: 30
OUTPUT:
  DIR: './output_dir/sa_v0_attn_smooth_normed_softmax_adam_movi_1000e/'
TRAIN:
  OPTIMIZER: 'adam'
MODEL:
  SLOT:
    ATTN_SMOOTH: "normed_softmax"