_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'clevr' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'MOVi', 'movi']
  IMG_SIZE: 64
  NUM_WORKERS: 30
OUTPUT:
  DIR: './output_dir/clv6_ask_ippe123_1.0_0.75/'
TRAIN:
  EPOCHS: 1000
  BATCH_SIZE: 256
  POS_LOSS_WEIGHT: 0.01
  OPTIMIZER: 'adam'
WEAK_SUP:
  TYPE: "bbox_center"
  USE_NO_OBJ: False
  RANDOM_PROP: 0.75
  RAND_POS_TYPE: "uniform" # it can be "standard_gaussian"
  INIT_USING_SUP: False
  SPLIT:
    RATIO: 1.0
POS_PRED:
  USE_POS_PRED: True
  USE_GT: True
  POS_ENC_MODE: "learnable"
  LOCATIONS: [1,2,3] # -1 to last one, 1,2,3,.. to iteration number # TODO: name of variable?
MODEL:
  SLOT:
    ATTN_SMOOTH: "normed_softmax"