_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'clevr' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'msn', 'MSN']
  IMG_SIZE: 128
  NUM_WORKERS: 30
OUTPUT:
  DIR: './output_dir/jw_v1_clevr6_1000e/'
MODEL:
  GLOBAL_SLOT:
    USE_GS: True
    ABSTRACT_SIZE: 4
    DEC_INIT_SIZE: 4 # still studying on this.. 
WEAK_SUP:
  TYPE: "bbox_center"
  USE_NO_OBJ: False
  RANDOM_PROP: 0.75
  RAND_POS_TYPE: "uniform" # it can be "standard_gaussian"
  INIT_USING_SUP: False
  SPLIT:
    RATIO: 0.1
    TRAIN:
      MODE: 'epoch_ranges' # ['interval', 'epoch_ranges']
      INTERVAL: 0 
      DURATION: 0
      INTERVAL_START: 0
      EPOCH_RANGES: [[0, 200]]
POS_PRED:
  USE_POS_PRED: True
  USE_GT: True
  POS_ENC_MODE: "learnable"