_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'ptr' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'msn', 'MSN']
  IMG_SIZE: 128
  NUM_WORKERS: 30
OUTPUT:
  DIR: './output_dir/sa_base_pert_2_ptr_1000e/'
MODE:
  SLOT:
    PERT: 
      USE_PERT: True  
      SIGMA: 2