_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'ptr' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'msn', 'MSN']
  IMG_SIZE: 128
  NUM_WORKERS: 30
TRAIN:
  OPTIMIZER: 'adam'
OUTPUT:
  DIR: './output_dir/sa_base_adam_ptr_1000e/'

