_BASE_: "../SA_base.yaml"
SEED: 0
DEVICE: 'cuda'
DATA:
  TYPE: 'ptr' # ['clevr', 'CLEVR', 'ptr', 'PTR', 'msn', 'MSN']
  IMG_SIZE: 128
  NUM_WORKERS: 30
OUTPUT:
  DIR: './output_dir/sa_base_use_low_res_attn_0.25_ptr_1000e/'
MODEL:
  FEAT_PYRAMID:
    AGGREGATION: 'attn' # ['slot', 'attn']
    RES_RATE_LIST: [1., 0.25] # use can add element (candidate: 1, 0.5, 0.25, 0.125) as much as NUM_LOW_RES
